#!/bin/bash

NAME=bsp-devkit
MIRRORDIR=$HOME/ssd/localmirror
XDTDIR=$HOME/ssd/xdt
SHAREDDIR=$HOME/devel/docker/share

docker run --publish=2222:22 --publish=8000:8000 --publish=69:69/udp --detach=true --hostname=$NAME --name=$NAME \
	--privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
	-v $MIRRORDIR:/home/devel/mirror \
	-v $SHAREDDIR:/home/devel/share \
	-v $XDTDIR:/xdt \
	-it docker.iot.bzh/iotbzh/worker_bsp_base:2.0

echo "Copying your identity to container $NAME:"
sleep 2
ssh-copy-id -p 2222 devel@localhost

scp -P 2222  $HOME/.gitconfig devel@localhost:~/

echo "You can now login using:"
echo "   ssh -p 2222 devel@$(hostname)"

